name: Test
on:
  workflow_dispatch:

  push:
    branches: 
      - '**'

jobs:
  test:
    name: Setup and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: globalid-connect/node
            name: "Connect Node example"
            id: connect-node
          # just add additional entries here for additional examples to build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - name: Cache dependencies ${{ matrix.name }}
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.context }}/node_modules
          key:  ${{ matrix.id }}-${{ hashFiles('${{ matrix.context }}/package-lock.json') }}
      - name: Install dependencies for ${{ matrix.name }}
        shell: sh
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci --ignore-scripts
        working-directory: ${{ matrix.context }}
      - name: Test ${{ matrix.name }}
        working-directory: ${{ matrix.context }}
        run: npm run test
